### PR TITLE
Added Support Vector Machine

### PR DESCRIPTION
**Pull request by umang537**

### CODE REVIEW

**Comment by sidhantagar** [comment]
please add “fixes #<issue_number>” as a comment of the PR

**Comment by umang537** [comment]
fixed #15

**Comment by sidhantagar** [comment]
Please copy the PR URL and submit it on https://contrihub21.herokuapp.com/

**Comment by umang537** [comment]
> Please copy the PR URL and submit it on https://contrihub21.herokuapp.com/

Exactly where do I need to submit the URL on the contrihub website?

**Comment by sidhantagar** [comment]
> > Please copy the PR URL and submit it on https://contrihub21.herokuapp.com/
> 
> Exactly where do I need to submit the URL on the contrihub website?

Refer to the CC briefing video at 2:01:40 (It is under the profile tab on contrihub.)

**Pull request merged**
