### PR TITLE
Added Support Vector Machine Notebook

### LINKED ISSUE #2: Add SVM (Support Vector Machine)
You have to add Support Vector Machine in a similar way to other algorithms that have been implemented on this platform.

### PR DESCRIPTION
**Pull request by AnuragGupta806**
Fixes #2 
Added relevant theory for SVM with proper images.

### CODE REVIEW

**Comment by m1-key** [comment]
You have to add an SVM section similar to other algorithms on the front page. When the user clicks this, then it should take him/her to a page similar to when the user clicks on Linear Regression or Thug life, etc..

**Comment by AnuragGupta806** [comment]
Do I need to create the playground also? I don't know how to do that 😕

**Comment by m1-key** [comment]
No, you don't need to make playground

**Comment by AnuragGupta806** [comment]
I have added the SVM algo to frontend and displayed its Jupyter Notebook just like other algorithms

**Comment by m1-key** [comment]
Cool, try to add some screenshots of the output. For further PRs, add some screenshots in the comment. 
Good work.

**Pull request merged**
