### PR TITLE
navbar corrected

### LINKED ISSUE #4: Create a new navbar
The current navbar is not working properly and is unresponsive for few sections. Fix that with proper documentation.

### PR DESCRIPTION
**Pull request by taru2001**
Fixes #4
Initially in the top navbar whenever we hover the mouse in the links of navbar switch very quickly if the mouse is between two links but now it is corrected.
navbar corrected

### CODE REVIEW

**Comment by abhaykatheria** [comment]
pls add proper description and a screenshot of what your pr does :)

**Comment by taru2001** [comment]
> pls add proper description and a screenshot of what your pr does :)

done sir

**Comment by m1-key** [comment]
> Initially in the top navbar whenever we hover the mouse in the links of navbar switch very quickly if the mouse is between two links but now it is corrected. 

Your first line should contain this format "Fixes issue_number_you fixed", so edit your initial comment and add this line.

**Comment by taru2001** [comment]
> > Initially in the top navbar whenever we hover the mouse in the links of navbar switch very quickly if the mouse is between two links but now it is corrected.
> 
> Your first line should contain this format "Fixes issue_number_you fixed", so edit your initial comment and add this line.

done sir

**Pull request merged**
