### PR TITLE
Added notebook for Object Classification

### LINKED ISSUE #8: Add jupyter notebook for Object Classification
Create a jupyter notebook for object classification similar to Linear Regression.

### PR DESCRIPTION
**Pull request by kunal2812**
Fixes #8  
Colab Link [here](https://colab.research.google.com/drive/1CPu32TeO4MEVhofssWAThyS47RUIUO1m?usp=sharing)

### CODE REVIEW

**Comment by m1-key** [comment]
Add this notebook to the code also, i.e when the user opens object classification, this notebook should appear similar to other algos.

**Comment by kunal2812** [comment]
Let me know if still there are issues, I couldn't test the code due to system incompatibility

**Comment by m1-key** [comment]
Try to run the code and attach screenshots here so that I can verify

**Comment by kunal2812** [comment]
Please check

image

image

image

image

Resolving Conflicts

**Comment by m1-key** [comment]
LGTM

**Pull request merged**
